spring.application.name=tienda

#Se define el puerto por donde escuvha el servidor web
server.port=80

#Se define el formato del log fecha/hora
logging.patter.dateformat=hh:mm

#Se avita mostrar el banner SPRING en el log
spring.main.banner-mode=off

#Se evita el uso de cache en desarrollo y se activa en produccion
spring.thymeleaf.cache=false
